#!/bin/bash

cd ~/
echo seshan | sudo -S ls /root

sudo killall python
sshpass -p maker ssh robot@10.42.0.3 'killall python2 ; python2 -u ~/socketscorer.py' | sudo python pacman.py &
sshpass -p maker ssh robot@10.42.0.3 './reset.sh'

sleep 50000000
