#!/bin/bash

sshpass -p maker ssh robot@10.42.5.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.4.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.3.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.2.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.1.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.0.1 'echo maker | sudo -S poweroff'&
sleep 1
