#!/bin/bash

sshpass -p maker ssh robot@192.168.0.6 'echo maker | sudo -S poweroff' &
sleep 1
sshpass -p maker ssh robot@192.168.0.5 'echo maker | sudo -S poweroff' &
sleep 1
sshpass -p maker ssh robot@192.168.0.4 'echo maker | sudo -S poweroff' &
sleep 1
sshpass -p maker ssh robot@192.168.0.3 'echo maker | sudo -S poweroff' &
sleep 1
sshpass -p maker ssh robot@192.168.0.2 'echo maker | sudo -S poweroff' &
sleep 1
sshpass -p maker ssh robot@192.168.0.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.5.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.4.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.3.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.2.1 'echo maker | sudo -S poweroff'&
sleep 1
sshpass -p maker ssh robot@10.42.1.1 'echo maker | sudo -S poweroff'&
sleep 1
echo "Please wait..."
sleep 20
echo maker | sudo -S poweroff
